//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSCodingStudy.EFSqlDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RobotUserCode
    {
        public int UserId { get; set; }
        public int LessonId { get; set; }
        public string Code { get; set; }
    
        public virtual RobotLessons RobotLessons { get; set; }
        public virtual Users Users { get; set; }
    }
}
