//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSCodingStudy.EFSqlDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RobotLessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RobotLessons()
        {
            this.RobotUserCode = new HashSet<RobotUserCode>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Task { get; set; }
        public string Pattern { get; set; }
        public int StartX { get; set; }
        public int StartY { get; set; }
        public bool HelpAPIMove { get; set; }
        public bool HelpAPICheck { get; set; }
        public bool HelpAPIDraw { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RobotUserCode> RobotUserCode { get; set; }
    }
}
